#############################
#	DEVELOPMENT STAGE		#
#############################
FROM node:20-alpine AS development

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

 # Copy settings
COPY tsconfig.json tsconfig.app.json tsconfig.node.json ./
COPY vite.config.ts postcss.config.js ./

# Copy sources
COPY public ./public
COPY index.html ./

EXPOSE 8080

CMD ["npm", "run", "dev"]
