### Example POST request to the backend
GET http://127.0.0.1:4241/ HTTP/1.1


### Test if the backend and database are healthy
GET http://127.0.0.1:4241/healthcheck HTTP/1.1
Accept: application/json

### Test seeded users in database. Check console for UUID.
GET http://127.0.0.1:4241/test/<UUID> HTTP/1.1
Accept: application/json

